
spring:
  application:
    name: eureka-server

server:
  port: 8083

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      dafaultZone: http://localhost:8083/eureka

#default port for eureka server - 8761

