server:
  port:8090

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
      - id: studentModule
        uri: lb://student-service   #this replaced uri: http://localhost:8080/ from gateway yml
        predicates:
        - Path=/student/**
      - id: courseModule
        uri: lb://course-service
        predicates:
        - Path=/course/**
#          filters:
#          - name: Requestsize
#            args:
#              Maxsize: 5000000
#uri - universal resource identifier

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8083/eureka