server:
  port : 8081

spring:
  application:
    name : course-service

  profiles:
    active : dev

  jpa:
    hibernate:
      ddl-auto : update

  datasource:
    url : jdbc:mysql://localhost:3306/db_course?createDatabaseIfNotExist=true
    driver-class-name : com.mysql.cj.jdbc.Driver
    username : root
    password : Abhis@123654

environment: COMMON
#this needs to be added after eureka registry service creation
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8083/eureka

#application.properties
#spring.profiles.active=dev
#environment=COMMON
#spring.jpa.hibernate.ddl-auto=update
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.url=jdbc:mysql://localhost:3306/db_course?createDatabaseIfNotExist=true
#spring.datasource.username=root
#spring.datasource.password=Abhis@123654